/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AirButton: typeof import('./src/components/AirButton.vue')['default']
    AirCheckbox: typeof import('./src/components/AirCheckbox.vue')['default']
    AirFilter: typeof import('./src/components/AirFilter.vue')['default']
    AirLogo: typeof import('./src/components/AirLogo.vue')['default']
    AirPrice: typeof import('./src/components/AirPrice.vue')['default']
    AirSkeleton: typeof import('./src/components/AirSkeleton.vue')['default']
    AirSorting: typeof import('./src/components/AirSorting.vue')['default']
    AirTicket: typeof import('./src/components/AirTicket.vue')['default']
    AirTicketsList: typeof import('./src/components/AirTicketsList.vue')['default']
    AirTicketsProvider: typeof import('./src/components/AirTicketsProvider.vue')['default']
    IconArrow: typeof import('./src/components/icons/IconArrow.vue')['default']
    IconCheck: typeof import('./src/components/icons/IconCheck.vue')['default']
  }
}
